name: "Deploy to GCP infra"

on:
  push:
    branches:
    - main  # Change this to match your main branch name
    tags:
      - 'v*'  # Matches tags like v1.x.x
env:
  IMAGE_NAME: 'xpto-plataforma'
  PROJECT_ID: 'laboratorio-mba-sirius-cecd'
  AR_REPO_LOCATION: 'us-central1'
  AR_URL: 'us-central1-docker.pkg.dev/laboratorio-mba-sirius-cecd/xpto-registry'
  SERVICE_ACCOUNT: 'githubactionst@laboratorio-mba-sirius-cecd.iam.gserviceaccount.com' 
  WORKLOAD_IDENTITY_PROVIDER: 'projects/269232469558/locations/global/workloadIdentityPools/xpto-pool/providers/githubactions-provider'

jobs:
  build-and-push:
    name: Build && Push && Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker image tag
        id: set_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.2
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

     
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/xpto-registry/xpto-registry:${{ steps.set_tag.outputs.tag }} -f Dockerfile .
      
      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/xpto-registry/xpto-registry:${{ steps.set_tag.outputs.tag }}
      
      - name: Deploy to Cloud Run
        run: |-
             gcloud run deploy xpto-plataforma --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/xpto-plataforma/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }}  \
             --platform managed --region me-central1 --concurrency 1 \
             --min-instances 1 --max-instances 1 --port 80 --platform managed --allow-unauthenticated